; Script generated by Antigravity for Universe
#define MyAppName "Universe"
#define MyAppVersion "2.0.2"
#define MyAppPublisher "Notbanzz"
#define MyAppURL "https://universe-update-server.onrender.com"
#define MyAppExeName "Universe.exe"

[Setup]
AppId={{A1B2C3D4-E5F6-7890-1234-567890ABCDEF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=Installer
OutputBaseFilename=Universe_Setup_v{#MyAppVersion}
SetupIconFile=universe.ico
Compression=lzma2/ultra64
SolidCompression=yes
CloseApplications=no
RestartApplications=no
WizardStyle=modern
WizardImageFile=Installer\WizModernImage.bmp
WizardSmallImageFile=Installer\WizModernSmallImage.bmp

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Files]
; Main Executable
Source: "bin\Release\net48\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; Dependencies (DLLs, configs, etc.)
Source: "bin\Release\net48\*.dll"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "bin\Release\net48\*.config"; DestDir: "{app}"; Flags: ignoreversion
; Icon
Source: "universe.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\universe.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\universe.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall

[Code]
// Import DWM API for Dark Title Bar
function DwmSetWindowAttribute(hwnd: HWND; dwAttribute: DWORD; var pvAttribute: Integer; cbAttribute: DWORD): Integer;
external 'DwmSetWindowAttribute@dwmapi.dll stdcall delayload';

// Kill previous process instantly before installing to avoid Windows Restart Manager lag
function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
begin
  Exec('taskkill.exe', '/F /IM Universe.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec('taskkill.exe', '/F /IM NoFences.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Sleep(150);
  Result := '';
end;

procedure InitializeWizard();
var
  DarkModeVal: Integer;
begin
  WizardForm.Font.Name := 'Segoe UI';

  try
    DarkModeVal := 1;
    if DwmSetWindowAttribute(WizardForm.Handle, 20, DarkModeVal, 4) <> 0 then
      DwmSetWindowAttribute(WizardForm.Handle, 19, DarkModeVal, 4);
  except
  end;
end;
