; Script generated by Antigravity for NoFences
; Script generated by Antigravity for NoFences
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Universe"
#define MyAppVersion "2.0"
#define MyAppPublisher "Notbanzz"
#define MyAppURL "https://github.com/Notbanzz/NoFences"
#define MyAppExeName "Universe.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A1B2C3D4-E5F6-7890-1234-567890ABCDEF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=Installer
OutputBaseFilename=Universe_Setup_v2.0
SetupIconFile=d:\PROGRAMAS_MIOS\NoFences\NoFences\universe.ico
Compression=lzma
SolidCompression=yes
CloseApplications=yes
RestartApplications=yes
WizardStyle=modern
WizardResizable=yes
WizardImageFile=d:\PROGRAMAS_MIOS\NoFences\NoFences\Installer\WizModernImage.bmp
WizardSmallImageFile=d:\PROGRAMAS_MIOS\NoFences\NoFences\Installer\WizModernSmallImage.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Main Executable
Source: "bin\Release\net48\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; Dependencies (DLLs, configs, etc.)
Source: "bin\Release\net48\*.dll"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "bin\Release\net48\*.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net48\*.config"; DestDir: "{app}"; Flags: ignoreversion
; Icon
Source: "universe.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\universe.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\universe.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
